countries: 
    AFG
    ALB
    DZA
    AND
    AGO
    ATG
    ARG
    ARM
    ABW
    ASM
    AUS
    AUT
    AZE
    BHS
    BGD
    BRB
    BDI
    BEL
    BEN
    BMU
    BTN
    BIH
    BLZ
    BLR
    BOL
    BWA
    BRA
    BHR
    BRN
    BGR
    BFA
    CAF
    KHM
    CAN
    CYM
    COG
    TCD
    CHL
    CHN
    CIV
    CMR
    COD
    COK
    COL
    COM
    COR
    CPV
    CRI
    HRV
    CUB
    CYP
    CZE
    DNK
    DJI
    DMA
    DOM
    ECU
    EGY
    ERI
    SLV
    ESP
    EST
    ETH
    FJI
    FIN
    FRA
    FSM
    GAB
    GMB
    GBR
    GNB
    GEO
    GNQ
    DEU
    GHA
    GRC
    GRD
    GTM
    GIN
    GUM
    GUY
    HTI
    HKG
    HND
    HUN
    IDN
    IND
    IRN
    IRL
    IRQ
    ISL
    ISR
    VIR
    ITA
    VGB
    JAM
    JOR
    JPN
    KAZ
    KEN
    KGZ
    KIR
    N.D.
    KOR
    SAU
    KWT
    LAO
    LVA
    LBY
    LBN
    LBR
    LCA
    LSO
    LIE
    LTU
    LUX
    MDG
    MAR
    MYS
    MWI
    MDA
    MDV
    MEX
    MNG
    MHL
    MKD
    MLI
    MLT
    MNE
    MCO
    MOZ
    MUS
    MRT
    MMR
    NAM
    NIC
    NLD
    NPL
    NGA
    NER
    NOR
    NRU
    NZL
    N.D.
    OMN
    PAK
    PAN
    PRY
    PER
    PHL
    PSE
    PLW
    PNG
    POL
    PRT
    PRK
    PRI
    QAT
    ROU
    ZAF
    RUS
    RWA
    WSM
    SEN
    SYC
    SGP
    KNA
    SLE
    SVN
    SMR
    SLB
    SOM
    SRB
    LKA
    SSD
    STP
    SDN
    CHE
    SUR
    SVK
    SWE
    SWZ
    SYR
    TZA
    TON
    THA
    TJK
    TKM
    TLS
    TGO
    TWN
    TTO
    TUN
    TUR
    TUV
    ARE
    UGA
    UKR
    URY
    USA
    UZB
    VUT
    VEN
    VNM
    VCT
    YEM
    ZMB
    ZWE